# Generated by Django 4.0.1 on 2022-05-28 04:44

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import ocorrencia.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ativo'), (2, 'Inativo')], default=1)),
                ('username', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('local', models.CharField(max_length=255, verbose_name='Local do ocorrência')),
                ('coordenadaX', models.CharField(max_length=255, null=True, verbose_name='Coordenadas X')),
                ('coordenadaY', models.CharField(max_length=255, null=True, verbose_name='Coordenadas Y')),
                ('centro', models.PositiveSmallIntegerField(choices=[(1, 'Biblioteca Central'), (2, 'CIn'), (3, 'SSI')])),
                ('referencia', models.CharField(max_length=255, null=True, verbose_name='Local de referência')),
                ('data', models.DateTimeField(verbose_name='Data e hora')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Agressão'), (2, 'Furto'), (3, 'Roubo')])),
                ('descricao', models.TextField(max_length=255, null=True, verbose_name='Descrição da ocorrência')),
                ('envolvidoNome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do envolvido')),
                ('envolvidos', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Suspeito'), (2, 'Vitima')], null=True)),
                ('genero', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Feminino'), (2, 'Masculino'), (3, 'Outros')], null=True)),
                ('cpf', models.IntegerField(blank=True, null=True, verbose_name='CPF do envolvido')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email do envolvido')),
                ('fone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone do envolvido')),
                ('imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to=ocorrencia.models.get_file_path, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
            },
        ),
        migrations.CreateModel(
            name='PassagemPlatao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('data', models.DateTimeField(verbose_name='Data e hora')),
                ('descricao', models.TextField(max_length=255, null=True, verbose_name='Descrição da plantão')),
            ],
            options={
                'verbose_name': 'Passagem de Plantão',
                'verbose_name_plural': 'Passagens de Plantão',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('perfil', models.PositiveSmallIntegerField(choices=[(1, 'Administrador'), (2, 'Gestor'), (3, 'Inspetor'), (4, 'Notificante')])),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ocorrencia.usuario')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('ocorrencia.user', models.Model),
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
