# Generated by Django 4.0.1 on 2022-04-23 19:03

from django.db import migrations, models
import ocorrencia.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('coordenadaX', models.CharField(max_length=200, verbose_name='Coordenadas X')),
                ('coordenadaY', models.CharField(max_length=200, verbose_name='Coordenadas Y')),
                ('centro', models.CharField(choices=[('Almoxarifa-do-central', 'Almoxarifado Central'), ('Arquealogia', 'Arquealogia'), ('Apoio-pista-de-cooper', 'Apaio Pista de Cooper'), ('Biblioteca-central', 'Biblioteca Central'), ('Bloco-compartilhado-ccb', 'Bloco CoSSmpartilhado-CCB'), ('Bloco-compartilhados-outros', 'Bloco Compartilhado-CFCH/CE/CCSA')], max_length=200, verbose_name='Centro')),
                ('referencia', models.CharField(max_length=200, null=True, verbose_name='Local de referência')),
                ('data', models.DateTimeField(verbose_name='Data e hora')),
                ('tipo', models.CharField(choices=[('Agressao', 'Agressão'), ('Roubo', 'Roubo'), ('Furto', 'Furto')], max_length=200, verbose_name='Tipo da ocorrência')),
                ('descricao', models.TextField(max_length=200, null=True, verbose_name='Descrição da ocorrência')),
                ('envolvidoNome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do envolvido')),
                ('tipoEnvolvido', models.CharField(blank=True, choices=[('Suspeito', 'Suspeito'), ('Vitima', 'Vitima')], max_length=200, null=True, verbose_name='Tipo do envolvido')),
                ('genero', models.CharField(blank=True, choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], max_length=200, null=True, verbose_name='Gênero do envolvido')),
                ('cpf', models.IntegerField(blank=True, null=True, verbose_name='CPF do envolvido')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email do envolvido')),
                ('fone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone do envolvido')),
                ('imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to=ocorrencia.models.get_file_path, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
            },
        ),
    ]
