# Generated by Django 4.0.1 on 2022-04-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassagemPlatao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('data', models.DateTimeField(verbose_name='Data e hora')),
                ('descricao', models.TextField(max_length=255, null=True, verbose_name='Descrição da plantão')),
            ],
            options={
                'verbose_name': 'Passagem de Plantão',
                'verbose_name_plural': 'Passagens de Plantão',
            },
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='centro',
            field=models.CharField(choices=[('Almoxarifa-do-central', 'Almoxarifado Central'), ('Arquealogia', 'Arquealogia'), ('Apoio-pista-de-cooper', 'Apaio Pista de Cooper'), ('Biblioteca-central', 'Biblioteca Central'), ('Bloco-compartilhado-ccb', 'Bloco CoSSmpartilhado-CCB'), ('Bloco-compartilhados-outros', 'Bloco Compartilhado-CFCH/CE/CCSA')], max_length=255, verbose_name='Centro'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='coordenadaX',
            field=models.CharField(max_length=255, verbose_name='Coordenadas X'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='coordenadaY',
            field=models.CharField(max_length=255, verbose_name='Coordenadas Y'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='descricao',
            field=models.TextField(max_length=255, null=True, verbose_name='Descrição da ocorrência'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='genero',
            field=models.CharField(blank=True, choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], max_length=255, null=True, verbose_name='Gênero do envolvido'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='referencia',
            field=models.CharField(max_length=255, null=True, verbose_name='Local de referência'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='tipo',
            field=models.CharField(choices=[('Agressao', 'Agressão'), ('Roubo', 'Roubo'), ('Furto', 'Furto')], max_length=255, verbose_name='Tipo da ocorrência'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='tipoEnvolvido',
            field=models.CharField(blank=True, choices=[('Suspeito', 'Suspeito'), ('Vitima', 'Vitima')], max_length=255, null=True, verbose_name='Tipo do envolvido'),
        ),
    ]
